# Check `docs/pipeline.md` to get info about this file

resources:
- name: andrey-hellokite-repository
  type: git
  source:
    uri: https://github.com/andreymakovenko/hellokite
    branch: master

- name: andrey-hellokite-image
  type: docker-image
  source:
    repository: gcr.io/helios-devel/andrey-hellokite
    username: {{docker_username}}
    password: {{docker_password}}

jobs:
- name: andrey-hellokite
  serial: true
  plan:
  - get: andrey-hellokite-repository
    trigger: true
  - put: andrey-hellokite-image
    params:
      build: andrey-hellokite-repository
